services:
  - serviceId: Sarashina2-Vsion-8b|R
    description: a Japanese Large Vision Language Model trained by SB Intuitions.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstructionWithImage
    url: https://huggingface.co/sbintuitions/sarashina2-vision-8b
    license: mit
    properties:
      commands:
        - bash
        - run_repl_sarashina.sh
        - "sbintuitions/sarashina2-vision-8b"
      requiredGpuMemoryMBs: [20041]

  - serviceId: Sarashina2-Vsion-14b|R
    description: a Japanese Large Vision Language Model trained by SB Intuitions.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstructionWithImage
    url: https://huggingface.co/sbintuitions/sarashina2-vision-14b
    license: mit
    properties:
      commands:
        - bash
        - run_repl_sarashina.sh
        - "sbintuitions/sarashina2-vision-14b"
      requiredGpuMemoryMBs: [32421]

  - serviceId: InternVL3-8b|R
    description: We introduce InternVL3, an advanced multimodal large language model (MLLM) series that demonstrates superior overall performance.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstructionWithImage
    url: https://huggingface.co/OpenGVLab/InternVL3-8B
    license: apache-2.0
    properties:
      commands:
        - bash
        - run_repl_internvl3.sh
        - "OpenGVLab/InternVL3-8B"
      requiredGpuMemoryMBs: [25003]

  - serviceId: InternVL3-14b|R
    description: We introduce InternVL3, an advanced multimodal large language model (MLLM) series that demonstrates superior overall performance.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstructionWithImage
    url: https://huggingface.co/OpenGVLab/InternVL3-14B
    license: apache-2.0
    properties:
      commands:
        - bash
        - run_repl_internvl3.sh
        - "OpenGVLab/InternVL3-14B"
      requiredGpuMemoryMBs: [35657]
