version: '3'

services:
  service:
    build: ./build
    working_dir: /work
    volumes:
      - .:/work
      - ../cache:/root/.cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
