version: '3'

services:
  service:
    build: ./build
    working_dir: /workspace/magic-animate
    volumes:
      - .:/work
      - ../cache:/root/.cache
      - ./output:/workspace/magic-animate/samples
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
