version: '3'

services:
  service:
    build: ./build
#    environment:
#      HUGGINGFACE_TOKEN: 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
    working_dir: /work
    volumes:
      - ../cache/huggingface:/root/.cache/huggingface
      - .:/work
