version: '3'

services:
  service:
    build: ./build
    working_dir: /workspace/IDM-VTON-hf
    volumes:
      - ../_common/gpuinfo.py:/workspace/IDM-VTON-hf/gpuinfo.py
      - ./sample.py:/workspace/IDM-VTON-hf/sample.py
      - .:/work
      - ../cache:/root/.cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
