common:
  license: Apache v2.0

services:
  - serviceId: Mistral7bV0.1|R
    description: "The Mistral-7B-v0.1 Large Language Model (LLM) is a pretrained generative text model with 7 billion parameters. "
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    url: https://huggingface.co/mistralai/Mistral-7B-v0.1
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - mistralai/Mistral-7B-v0.1
      requiredGpuCount: 1

  - serviceId: Mistral7bInstructV0.1|R
    description: "The Mistral-7B-Instruct-v0.1 Large Language Model (LLM) is a instruct fine-tuned version of the Mistral-7B-v0.1 generative text model using a variety of publicly available conversation datasets."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    url: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - mistralai/Mistral-7B-Instruct-v0.1
      requiredGpuCount: 1

  - serviceId: Mistral7bInstructV0.1TI|R
    description: "The Mistral-7B-Instruct-v0.1 Large Language Model (LLM) is a instruct fine-tuned version of the Mistral-7B-v0.1 generative text model using a variety of publicly available conversation datasets."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    url: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1
    properties:
      commands:
        - bash
        - run_instruction_repl.sh
        - mistralai/Mistral-7B-Instruct-v0.1
      requiredGpuCount: 1
