common:
  license: openrail++

services:
  - serviceId: SDXLBase_DS_0_21_0|R
    description: "SDXL consists of an ensemble of experts pipeline for latent diffusion: In a first step, the base model is used to generate (noisy) latents, which are then further processed with a refinement model (available here: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/) specialized for the final denoising steps. Note that the base model can be used as a standalone module."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0
    properties:
      commands:
        - bash
        - run_repl_sdxlbase.sh
        - stabilityai/stable-diffusion-xl-base-1.0
      requiredGpus: 1

  - serviceId: SDXLBaseWithRefiner_DS_0_21_0|R
    description: "SDXL consists of an ensemble of experts pipeline for latent diffusion: In a first step, the base model (available here: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) is used to generate (noisy) latents, which are then further processed with a refinement model specialized for the final denoising steps."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0
    properties:
      commands:
        - bash
        - run_repl_sdxlrefiner.sh
        - stabilityai/stable-diffusion-xl-base-1.0
        - --refinerModel
        - stabilityai/stable-diffusion-xl-refiner-1.0
      requiredGpus: 1

  - serviceId: SDXLBaseWithLora_Ikea_DS_0_21_0|R
    description: "Ikea Instructions - LoRA - SDXL"
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    url: https://huggingface.co/ostris/ikea-instructions-lora-sdxl
    properties:
      commands:
        - bash
        - run_repl_sdxllora.sh
        - stabilityai/stable-diffusion-xl-base-1.0
        - --loraModel
        - ostris/ikea-instructions-lora-sdxl
      requiredGpus: 1

  - serviceId: Wuerstchen_DS_0_21_0|R
    description: "Würstchen is a diffusion model, whose text-conditional model works in a highly compressed latent space of images."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    license: mit
    url: https://huggingface.co/warp-ai/wuerstchen
    properties:
      commands:
        - bash
        - run_repl_wuerstchen.sh
        - warp-ai/wuerstchen
      requiredGpus: 1
