common:
  license: openrail++

services:
  - serviceId: SDXLBase_DS_0_21_0|R
    description: "SDXL consists of an ensemble of experts pipeline for latent diffusion: In a first step, the base model is used to generate (noisy) latents, which are then further processed with a refinement model (available here: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/) specialized for the final denoising steps. Note that the base model can be used as a standalone module."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0
    properties:
      commands:
        - bash
        - run_sdxlbase_repl.sh
        - stabilityai/stable-diffusion-xl-base-1.0
      requiredGpuCount: 1

  - serviceId: SDXLBaseWithRefiner_DS_0_21_0|R
    description: "SDXL consists of an ensemble of experts pipeline for latent diffusion: In a first step, the base model (available here: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0) is used to generate (noisy) latents, which are then further processed with a refinement model specialized for the final denoising steps."
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    url: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0
    properties:
      commands:
        - bash
        - run_sdxlrefiner_repl.sh
        - stabilityai/stable-diffusion-xl-base-1.0
        - --refinerModel
        - stabilityai/stable-diffusion-xl-refiner-1.0
      requiredGpuCount: 1

  - serviceId: SDXLBaseWithLora_Ikea_DS_0_21_0|R
    description: "Ikea Instructions - LoRA - SDXL"
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextImageGeneration
    url: https://huggingface.co/ostris/ikea-instructions-lora-sdxl
    properties:
      commands:
        - bash
        - run_sdxllora_repl.sh
        - stabilityai/stable-diffusion-xl-base-1.0
        - --loraModel
        - ostris/ikea-instructions-lora-sdxl
      requiredGpuCount: 1
