version: '3'

services:
  service:
    build: ./build
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
    working_dir: /workspace/reasoning-model
    volumes:
      - ../cache/huggingface:/root/.cache/huggingface
      - ./test.py:/workspace/reasoning-model/test.py
      - ../_common/gpuinfo.py:/workspace/reasoning-model/gpuinfo.py
