version: '3'

services:
  service:
    build: ./build
    working_dir: /work
    volumes:
      - ../cache/huggingface:/root/.cache/huggingface
      - .:/work
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
