common:
  description: Llama2をベースとして日本語能力を拡張するために追加事前学習を行ったモデル。
  license: LLAMA 2 Community License
  url: https://huggingface.co/elyza/ELYZA-japanese-Llama-2-7b

services:
  # completion services
  - serviceId: ELYZAJapaneseLlama2-7B|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BFast|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-fast
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BInstruct|TG|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-instruct
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BFastInstruct|TG|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-fast-instruct
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-13B|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-13b
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-13BFast|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-13b-fast
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-13BInstruct|TG|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-13b-instruct
      requiredGpuMemoryMBs: [26757]

  - serviceId: ELYZAJapaneseLlama2-13BFastInstruct|TG|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-13b-fast-instruct
      requiredGpuMemoryMBs: [27001]

  # instruction services
  - serviceId: ELYZAJapaneseLlama2-7BInstruct|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    properties:
      commands:
        - bash
        - run_instruction_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-instruct
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BFastInstruct|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    properties:
      commands:
        - bash
        - run_instruction_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-fast-instruct
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-13BInstruct|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    properties:
      commands:
        - bash
        - run_instruction_repl.sh
        - elyza/ELYZA-japanese-Llama-2-13b-instruct
      requiredGpuMemoryMBs: [26757]

  - serviceId: ELYZAJapaneseLlama2-13BFastInstruct|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    properties:
      commands:
        - bash
        - run_instruction_repl.sh
        - elyza/ELYZA-japanese-Llama-2-13b-fast-instruct
      requiredGpuMemoryMBs: [27001]
