common:
  description: Llama2をベースとして日本語能力を拡張するために追加事前学習を行ったモデル。
  license: LLAMA 2 Community License
  url: https://huggingface.co/elyza/ELYZA-japanese-Llama-2-7b

services:
  # completion services
  - serviceId: ELYZAJapaneseLlama2-7B|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BInstruct|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-instruct
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BFast|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-fast
      requiredGpuCount: 1

  - serviceId: ELYZAJapaneseLlama2-7BFastInstruct|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - elyza/ELYZA-japanese-Llama-2-7b-fast-instruct
      requiredGpuCount: 1

  # instruction services
