common:
  license: CC-BY-NC 4.0
  url: https://huggingface.co/turing-motors

services:
  - serviceId: HeronChatGitJaStableLmBase7bV0|R
    description: Heron GIT Japanese StableLM Base 7B is a vision-language model that can converse about input images.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplInstructionWithImage
    disabled: true
    properties:
      commands:
        - bash
        - run_generation_repl.sh
        - turing-motors/heron-chat-git-ja-stablelm-base-7b-v0
      requiredGpuCount: 1

  - serviceId: HeronChatGitElyzaFast7bV0|R
    description: Heron GIT Japanese ELYZA Llama 2 Fast 7B is a vision-language model that can converse about input images.
    url: https://huggingface.co/turing-motors/heron-chat-git-ELYZA-fast-7b-v0
    implementation: org.langrid.mlgridservices.service.impl.CmdReplInstructionWithImage
    disabled: false
    properties:
      commands:
        - bash
        - run_instruction_repl_gitllama.sh
        - turing-motors/heron-chat-git-ELYZA-fast-7b-v0
      requiredGpuCount: 1

  - serviceId: HeronChatGitLlama2-7bV0|R
    description: Heron GIT Llama 2 7B is a vision-language model that can converse about input images.
    url: https://huggingface.co/turing-motors/heron-chat-git-Llama-2-7b-v0
    implementation: org.langrid.mlgridservices.service.impl.CmdReplInstructionWithImage
    disabled: false
    properties:
      commands:
        - bash
        - run_instruction_repl_gitllama.sh
        - turing-motors/heron-chat-git-Llama-2-7b-v0
      requiredGpuCount: 1
