/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.langrid.jsservicegw;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class ApplicationTest {

  @Test
  void contextLoads() {
  }

}
