services:
  # instruction
  - serviceId: llama.cpp|SakanaAI-EvoLLM-JP-A-v1-7B_q5_K_M|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    description: an experimental general-purpose Japanese LLM.
    license: Apache License, Version 2.0
    url: https://huggingface.co/SakanaAI/EvoLLM-JP-A-v1-7B
    properties:
      commands:
        - bash
        - run_repl.sh
        - SakanaAI/EvoLLM-JP-A-v1-7B
        - mmnga/SakanaAI-EvoLLM-JP-A-v1-7B-gguf
        - "*q5_K_M.gguf"
      requiredGpuMemoryMBs: [5314]

  - serviceId: llama.cpp|SakanaAI-EvoLLM-JP-A-v1-7B_q8_0|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    description: an experimental general-purpose Japanese LLM.
    license: Apache License, Version 2.0
    url: https://huggingface.co/SakanaAI/EvoLLM-JP-A-v1-7B
    properties:
      commands:
        - bash
        - run_repl.sh
        - SakanaAI/EvoLLM-JP-A-v1-7B
        - mmnga/SakanaAI-EvoLLM-JP-A-v1-7B-gguf
        - "*q8_0.gguf"
      requiredGpuMemoryMBs: [7719]

  # chat
  - serviceId: llama.cpp|SakanaAI-EvoLLM-JP-A-v1-7B_q5_K_M|Chat|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplChat
    description: an experimental general-purpose Japanese LLM.
    license: Apache License, Version 2.0
    url: https://huggingface.co/SakanaAI/EvoLLM-JP-A-v1-7B
    properties:
      commands:
        - bash
        - run_repl.sh
        - SakanaAI/EvoLLM-JP-A-v1-7B
        - mmnga/SakanaAI-EvoLLM-JP-A-v1-7B-gguf
        - "*q5_K_M.gguf"
      requiredGpuMemoryMBs: [5314]

  - serviceId: llama.cpp|SakanaAI-EvoLLM-JP-A-v1-7B_q8_0|Chat|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplChat
    description: an experimental general-purpose Japanese LLM.
    license: Apache License, Version 2.0
    url: https://huggingface.co/SakanaAI/EvoLLM-JP-A-v1-7B
    properties:
      commands:
        - bash
        - run_repl.sh
        - SakanaAI/EvoLLM-JP-A-v1-7B
        - mmnga/SakanaAI-EvoLLM-JP-A-v1-7B-gguf
        - "*q8_0.gguf"
      requiredGpuMemoryMBs: [7719]

