version: '3'

services:
  service:
    build: ./build
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
    working_dir: /work
    volumes:
      - .:/work
      - ../_common/gpuinfo.py:/work/gpuinfo.py
