services:
  # completion
  - serviceId: llama-cpp|Karakuri-70b-chat-v0.1-q5_K_S|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    description: a pretrained language model that builds upon Llama 2.
    license: LLAMA 2 Community License, CC BY-SA 4.0
    url: https://huggingface.co/karakuri-ai/karakuri-lm-70b-v0.1
    properties:
      commands:
        - bash
        - run_repl.sh
        - karakuri-lm-70b-chat-v0.1-q5_K_S.gguf
      requiredGpus: 1

  # instruction
  - serviceId: llama-cpp|Karakuri-70b-chat-v0.1-q5_K_S|TI|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    description: a pretrained language model that builds upon Llama 2.
    license: LLAMA 2 Community License, CC BY-SA 4.0
    url: https://huggingface.co/karakuri-ai/karakuri-lm-70b-chat-v0.1
    properties:
      commands:
        - bash
        - run_repl.sh
        - karakuri-lm-70b-chat-v0.1-q5_K_S.gguf
      requiredGpus: 1

  # contextual question answering
  - serviceId: llama-cpp|Karakuri-70b-chat-v0.1-q5_K_S|CQA|R
    implementation: org.langrid.mlgridservices.service.impl.CmdReplContextualQuestionAnswering
    description: a pretrained language model that builds upon Llama 2.
    license: LLAMA 2 Community License, CC BY-SA 4.0
    url: https://huggingface.co/karakuri-ai/karakuri-lm-70b-chat-v0.1
    properties:
      commands:
        - bash
        - run_repl.sh
        - karakuri-lm-70b-chat-v0.1-q5_K_S.gguf
      requiredGpus: 1
