common:
  license: mit

services:
  # completion
  - serviceId: Phi2|TG|R
    description: a Transformer with 2.7 billion parameters.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextGeneration
    url: https://huggingface.co/microsoft/phi-2
    properties:
      commands:
        - bash
        - run_completion_repl.sh
        - microsoft/phi-2
      requiredGpus: 1

  # instruction
  - serviceId: Phi2|TI|R
    description: a Transformer with 2.7 billion parameters.
    implementation: org.langrid.mlgridservices.service.impl.CmdReplTextInstruction
    url: https://huggingface.co/microsoft/phi-2
    properties:
      commands:
        - bash
        - run_instruction_repl.sh
        - microsoft/phi-2
      requiredGpus: 1
