common:
  description: Test services.
  license: NONE
  url: NONE

services:
  - serviceId: TestVisualQuestionAnswering
    implementation: org.langrid.mlgridservices.service.impl.test.TestVisualQuestionAnswering
