version: '3'

services:
  service:
    build: ./build
    working_dir: /work
    volumes:
      - ../cache/huggingface:/root/.cache/huggingface
      - ../_common/gpuinfo.py:/work/gpuinfo.py
      - .:/work
